# this playbook is dedicated to ubuntu headless server environments
- hosts: localhost
  pre_tasks:
    - name: Update Apt
      become: true
      apt: update_cache=yes
      changed_when: False
  tasks:
    - import_tasks: tasks/core-packages.yml
    - import_tasks: tasks/zsh.yml
    - import_tasks: tasks/dotfiles.yml
    - import_tasks: tasks/tmux.yml
    - import_tasks: tasks/nvtop.yml
    - import_tasks: tasks/python.yml
    - import_tasks: tasks/nodejs.yml
    - import_tasks: tasks/neovim.yml
