# this playbook is dedicated to ubuntu laptop host environments
- hosts: localhost
  pre_tasks:
    - name: Update Apt
      become: true
      apt: update_cache=yes
      changed_when: False
  tasks:
    - include: tasks/core-packages.yml
    - include: tasks/gui-tools.yml
    - include: tasks/battery.yml
    - include: tasks/zsh.yml
    - include: tasks/powerline.yml
    - include: tasks/dotfiles.yml
    - include: tasks/tmux.yml
    - include: tasks/python.yml
    - include: tasks/rust.yml
    - include: tasks/nodejs.yml
    - include: tasks/neovim.yml
