- hosts: localhost
  pre_tasks:
    - name: Update Apt
      become: true
      apt: update_cache=yes
      changed_when: False
  tasks:
    - include: tasks/core-packages.yml
    - include: tasks/productivity-tools.yml
    - include: tasks/zsh.yml
    - include: tasks/powerline.yml
    - include: tasks/dotfiles.yml
    - include: tasks/python.yml
    - include: tasks/rust.yml
    - include: tasks/node.yml
    - include: tasks/neovim.yml
