- hosts: localhost
  pre_tasks:
    - name: Update Apt
      become: true
      apt: update_cache=yes
      changed_when: False
  tasks:
    - include: tasks/packages.yml
    - include: tasks/zsh.yml
