- hosts: localhost
  pre_tasks:
    - name: Check if homebrew is avaiable
      block:
        - name: try using homebrew in check_mode (no changes)
          homebrew:
            update_homebrew: true
          check_mode: true
        - name: Homebrew available
          debug:
            msg: Homebrew is installed
      rescue:
        - name: No homebrew
          debug:
            msg: Homebrew is not installed
    - name: Update homebrew
      community.general.homebrew:
        update_homebrew: true
  tasks:
    - include: tasks/macos_neovim.yml
    - include: tasks/macos_tmux.yml
    - include: tasks/macos_mosh.yml
