- name: Pull dwm-flexipatch repository
  ansible.builtin.git:
    repo: 'https://github.com/bakkeby/dwm-flexipatch.git'
    dest: "~/git/dwm-flexipatch"

- name: Build dwm-flexipatch
  become: true
  shell: make clean install

# needed to control and mute volume via XF86 keys
- name: Install PulseAudio
  become: true
  ansible.builtin.apt:
    name: ['pulseaudio']

# needed to control display brightness via XF86 keys
- name: Install brightnessctl
  become: true
  ansible.builtin.apt:
    name: ['brightnessctl']

- name: Register username for following task
  command: whoami
  changed_when: false
  become: false
  register: whoami

- name: Add user to video group to enable changing display brightness without sudo 
  ansible.builtin.user:
    name: "{{ whoami.stout }}"
    group: video
