  - name: Install GUI tools
    become: true
    ansible.builtin.apt:
      name: ['redshift', 'feh', 'flameshot']

  - name: Install programming GUI tools
    become: true
    ansible.builtin.apt:
      name: ['hotspot']

  - name: Install LibreOffice
    become: true
    ansible.builtin.apt:
      name: ['libreoffice']
