- name: Install GUI tools
  become: true
  ansible.builtin.apt:
    name: ['redshift', 'feh', 'flameshot']

- name: Install programming GUI tools
  become: true
  ansible.builtin.apt:
    name: ['hotspot']

- name: Install LibreOffice
  become: true
  ansible.builtin.apt:
    name: ['libreoffice']

# Brave browser installation steps
- name: Add Brave browser GPG key
  become: true
  ansible.builtin.get_url:
    url: https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
    dest: /usr/share/keyrings/brave-browser-archive-keyring.gpg
    mode: '0644'

- name: Add Brave browser repository
  become: true
  ansible.builtin.apt_repository:
    repo: deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg] https://brave-browser-apt-release.s3.brave.com/ stable main
    state: present
    filename: brave-browser-release

- name: Install Brave browser
  become: true
  ansible.builtin.apt:
    name: brave-browser
    update_cache: yes
    state: present
