- name: Install pyenv
  community.general.homebrew:
    name: pyenv
    state: present

# - name: Install pyenv-virtualenv
#   ansible.builtin.git:
#     repo: 'https://github.com/pyenv/pyenv-virtualenv.git'
#     dest: '~/.pyenv/plugins/pyenv-virtualenv'

- name: Install Poetry
  shell: curl -sSL https://install.python-poetry.org | sed 's/symlinks=False/symlinks=True/' | python3 -
