- name: Check if .oh-my-zsh directory exists
  stat:
   path: "{{ lookup('env', 'HOME') }}/.oh-my-zsh/"
  register: my_folder

- name: Echo if directory already existed
  debug:
    msg: "The oh-my-zsh directory already exist"
  when: my_folder.stat.exists

- name: Install Oh-My-Zsh if .oh-my-zsh directory does not exist
  shell: curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh > ~/.oh-my-installer && chmod +x ~/.oh-my-installer && ~/.oh-my-installer
  when: my_folder.stat.exists == false

- name: Install powerlevel10k
  ansible.builtin.include_tasks: jj_repo.yml
  vars:
    jj_repo_url: "https://github.com/romkatv/powerlevel10k.git"
    jj_repo_dest: "{{ lookup('env', 'HOME') }}/.oh-my-zsh/custom/themes/powerlevel10k"
      
- name: Install zsh-vi-mode
  ansible.builtin.include_tasks: jj_repo.yml
  vars:
    jj_repo_url: "https://github.com/jeffreytse/zsh-vi-mode"
    jj_repo_dest: "{{ lookup('env', 'HOME') }}/.oh-my-zsh/custom/plugins/zsh-vi-mode"

- name: Install zsh-autosuggestions
  ansible.builtin.include_tasks: jj_repo.yml
  vars:
    jj_repo_url: 'https://github.com/zsh-users/zsh-autosuggestions.git'
    jj_repo_dest: "{{ lookup('env', 'HOME') }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"

- name: Install zsh-fzf-history-search
  ansible.builtin.include_tasks: jj_repo.yml
  vars:
    jj_repo_url: 'https://github.com/joshskidmore/zsh-fzf-history-search'
    jj_repo_dest: "{{ lookup('env', 'HOME') }}/.oh-my-zsh/custom/plugins/zsh-fzf-history-search"

- name: Install zsh-syntax-highlighting
  ansible.builtin.include_tasks: jj_repo.yml
  vars:
    jj_repo_url: 'https://github.com/zsh-users/zsh-syntax-highlighting'
    jj_repo_dest: "{{ lookup('env', 'HOME') }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
