- name: Download nvm installer
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.4/install.sh
    dest: "{{ ansible_env.HOME }}/.nvm-install.sh"
    mode: '0755'

- name: Install nvm
  ansible.builtin.shell:
    cmd: "{{ ansible_env.HOME }}/.nvm-install.sh"
    creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"

- name: Remove nvm installer
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.nvm-install.sh"
    state: absent

- name: Install Node.js LTS
  ansible.builtin.shell:
    cmd: |
      export NVM_DIR="{{ ansible_env.HOME }}/.nvm"
      \. "$NVM_DIR/nvm.sh"
      nvm install lts
    creates: "{{ ansible_env.HOME }}/.nvm/versions/node"
