- name: Check if Cargo is Installed
  shell: command -v cargo
  register: cargo_exists
  ignore_errors: yes

- name: Download Cargo Installer
  when: cargo_exists is failed
  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: '0755'
    force: 'yes'
  tags:
    - rustup

- name: Install Rust and Cargo
  when: cargo_exists is failed
  shell: /tmp/sh.rustup.rs -y
  tags:
    - rust
