- name: Install tmux
  become: true
  ansible.builtin.apt:
      name: ['tmux']

- name: Clone TPM (Tmux Plugin Manager)
  ansible.builtin.git:
    repo: 'https://github.com/tmux-plugins/tpm'
    dest: "{{ lookup('env', 'HOME') }}/.tmux/plugins/tpm"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: master
