- name: Install typst from stable release
  ansible.builtin.shell: |
    source {{ ansible_env.HOME }}/.cargo/env
    cargo install --locked typst-cli
  args:
    executable: /bin/bash
    creates: "{{ ansible_env.HOME }}/.cargo/bin/typst"
