- name: Add Typst apt keyring
  become: true
  ansible.builtin.apt_key:
    url: https://typst.app/key.gpg
    state: present

- name: Add Typst apt repository
  become: true
  ansible.builtin.apt_repository:
    repo: deb https://typst.app/packages stable main
    state: present
    filename: typst

- name: Install typst
  become: true
  ansible.builtin.apt:
    name: typst
    state: present
